### ISSUE TITLE
Dont work on Firefox

### ISSUE THREAD

**Issue by lezzamat** [hand-dot/labelmake#36] opened 2021-07-20 12:34 UTC
my first browser is Firefox and don't work on it, it work ok in chrome

**Comment by hand-dot** [comment] 2021-07-23 05:47
thanks for the report. I'll check it.

**Comment by hand-dot** [comment] 2022-02-10 06:21
I checked but could not find where the problem was.
so, closing it.

Please create a new issue with instructions on how to reproduce the bug.

**Closed by hand-dot** 2022-02-10 06:21 UTC
