### ISSUE TITLE
Feature Request: Able to change font weight

### ISSUE THREAD

**Issue by normanwongcl** [hand-dot/labelmake#55] opened 2021-11-19 06:58 UTC
I would like to be able to change the font weight of the font that I am using.

![font weight](https://user-images.githubusercontent.com/34085667/142578913-b23fdd71-7cd9-4566-93fe-590f9598df1b.PNG)

**Comment by hand-dot** [comment] 2021-11-20 09:57
@normanwongcl 

Thanks for the suggestion.
Consider positively.

**Comment by normanwongcl** [comment] 2021-11-22 06:29
Duplicate of #30

**Comment by hand-dot** [comment] 2021-12-16 05:31
this issue is Duplicate of #30

so i'll close.

**Closed by hand-dot** 2021-12-16 05:31 UTC
